@startuml classes

class Partie implements Serializable {  
    - int id

    + int getId()
}

class PartieDB {
    + Partie load(int id)
    + Boolean save(ListCard listCard)
    + Boolean delete(int id)
}

PartieDB - Partie

abstract class Card {

    + CardType getCardType()
}

Card o-- CardType

enum CardType { 
    Black 
    White 
    Red 
    Blue
}

class ListCard implements Serializable {
    - int id

    + ListCard getListCard()
    + void addCard(Card card)
    + ListCard extract(int n)
}

ListCard -- "*" Card
Partie o-- ListCard

class TextCard extends Card {
    - String text

    + ImageText(String text)
    + String getText()
}

class ImageCard extends Card {
    - String url

    + ImageCard(String url)
    + String getUrl()
}

class ListCardDB {

    + ListCard load()
    + Boolean save(ListCard listCard)
    + Boolean delete(int id)
}

ListCardDB - ListCard

class Statistique {
    - double averageTimePerTurn;
    - double averageWordsPerTurn;
    - int numberOfErrors;

}

Partie o-- "2" Statistique

@enduml